### ISSUE TITLE
File perpetually marked as "unsaved"

### ISSUE THREAD

**Issue by Subcide** [BuilderIO/html-to-figma#1]
After importing a URL, the document I import into seems to get stuck in an unsaved state.  Closing Figma completely and reopening it never seem to lose any changes, but I need to click to discard any changes which is a bit scary.

**Comment by steve8708** [comment]
Hey @Subcide, thanks for reporting! I've been digging into this and have found the culprit, sometimes Figma lands in this state when it has trouble loading one of the images

I'm working on making a script to comb through the images and figure out which one Figma won't load and remove it. Will report back when I've found a reliable solution and the plugin is updated

**Comment by steve8708** [comment]
Ok! I isolated the problem to a bug in Figma where you can upload an SVG file as a background image, but then it breaks saving. I now detect SVGs and convert them to SVG layers instead

I published the latest version of the plugin with this fix, give it a try and let me know if you have any other issues!

**Comment by Subcide** [comment]
Thanks mate, the SVG issue I was going to file separately so glad to see they're related.  I'll re test later tonight.
