### ISSUE TITLE
Request: Allow user to specify cookies

### ISSUE THREAD

**Issue by matt-neill** [BuilderIO/html-to-figma#10]
Imagine a use case where you want to import the cart page from an ecommerce site populated with items.  Allowing the user to add a "cart_id" cookie would allow the plugin to return a screenshot from an existing cart.

Other use cases:
- Sites/apps protected by log ins
- Sites that have dynamic content based on a cookie (e.g. popups/promos)

**Comment by steve8708** [comment]
Ah yes, thanks for the feedback! The way I plan to handle use cases like this is to make a chrome extension where you can log in to a page (or do anything else on a page - like add items to cart and open the cart) and then parse and import that to Figma

Does that sound like a fitting solution to your request here as well?

**Comment by matt-neill** [comment]
Love it!

**Comment by steve8708** [comment]
Chrome extension has been created, just waiting on Google to approve it now 😃

**Comment by steve8708** [comment]
Chrome extension published https://chrome.google.com/webstore/detail/efjcmgblfpkhbjpkpopkgeomfkokpaim
