### ISSUE TITLE
Suggestion/thoughts about including user agent styles

### ISSUE THREAD

**Issue by limitlessloop** [BuilderIO/html-to-figma#22]
This is a really useful plugin for me because I'm working on a project which tries to calculate as much of the design, spacing font sizes etc dynamically. Because it's calculated dynamically it's hard to replicate in a design tool, so being able to import these into a design tool is really useful. So thank you!

One thing I noticed was that my project has a very loose style reset and so some default user-agent styles pass through. However, when the site is imported using the plugin to Figma those styles are not imported (at least this is what I think is happening), one example was font weights for headers.

This isn't too much of a pain for me as I can be more implicit in my reset to support these missing styles, but it made me think that there may be some sites that don't have an aggressive style reset and therefore will rely on those user agent styles. Is this something that's easy to support? You may then find more accurate results when you import websites. I guess the difficult part would be which user agent styles you import, at most maybe just any would be better than none.

Anyway, it's just an idea. I'd be interested to hear your thoughts.

**Comment by steve8708** [comment]
Hey @limitlessloop - have you tried using our [chrome extension](https://chrome.google.com/webstore/detail/html-to-figma/efjcmgblfpkhbjpkpopkgeomfkokpaim?hl=en-US)?

It captures the exact state of your browser window, so if I understand your issue correctly, you could use it in combination with a chrome extension that allows you to override the user agent (like [this one](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg?hl=en-US)) to capture pages with any user agent styles you like

**Comment by limitlessloop** [comment]
My apologies, it looks like it's not the issue I thought which was causing the font weight not to be imported.  The font weight seems to be because of a different issue.

Thanks though for sharing a link to the chrome extension, this would cover the scenario I originally had in mind.

I/you can close this issue and I can create another issue regarding the font weight which doesn't seem to be applying.
