### ISSUE TITLE
THIS PLUGIN IS AMAZING

### ISSUE THREAD

**Issue by davidlinc1** [BuilderIO/html-to-figma#28]
I cannot overstate the value of this to designers working to maintain prototypes of site pages or user flows in a large web application. Without this, there is only one pathway to maintaining 1:1 product-prototype parity: manual composition - or if you're lucky you have pre-created components to use. 

For me personally, my team has hundreds of pages to account for in prototype form. This was a HUGE TIME SAVER. Does it pull a perfect 1:1 recreation of the page every single time? No. But it gets most of the way there, almost every single time. After evaluating other options for going from HTML to vectorization, they were all extremely inconsistent, and all I wanted was to go from "html to figma". Then after all that I find this! Dang.

Thanks for making this.

**Comment by steve8708** [comment]
Thanks for the kind words @davidlinc1 ! Much appreciated!
