### ISSUE TITLE
Unsupported file format?

### ISSUE THREAD

**Issue by bendebnam** [BuilderIO/html-to-figma#32]
(I just realised what I did - move along - nothing to see here..)

**Comment by bendebnam** [comment]
Okay...

**Comment by BillSeitz** [comment]
what did you do! (Because I have the same issue!) https://twitter.com/BillSeitz/status/1583110003518423045

(commenting here for future silly people)

**Comment by bendebnam** [comment]
@BillSeitz I think I may have tried to drag the file into Figma where what should happen is using the plugin to open the file itself instead.
