### ISSUE TITLE
Text extraction regression

### ISSUE THREAD

**Issue by Subcide** [BuilderIO/html-to-figma#4]
Paragraphs of text seem to be in the wrong font size, and have loads of spaces added causing really strange text flow.

Tested on https://onfido.com/kyc/ which the text was working fine last week with.

**Comment by Subcide** [comment]
On further investigation, it appears as if the weird spaces are actually in the source, however it'd make sense if extra spaces were stripped as they are when the HTML renders.

**Comment by steve8708** [comment]
Ah yes, forgot this was here, but I noticed this as well from that URL you shared regarding SVGs and have fixed it and will push that soon!
