### ISSUE TITLE
My chrome extension doesnt function anymore. It only worked the first time

### ISSUE THREAD

**Issue by palakshah11** [BuilderIO/html-to-figma#43]

**Comment by steve8708** [comment]
Hey @palakshah11 - I've observed chrome extensions sometimes being spotty, but generally either restarting chrome, or if that doesn't work restarting your computer, generally resolves the issue

Can you try that and let us know if that resolves your issue?

**Comment by palakshah11** [comment]
Hi,
It did resolve my issue. Thanks for the quick help.


thanks a lot!
-
Palak Shah
User Experience Designer
Aubergine Solutions Pvt. Ltd.
<https://auberginesolutions.com/>Facebook
<https://www.facebook.com/auberginesolutions/> | LinkedIn
<https://www.linkedin.com/company/aubergine-solutions-pvt-ltd/>| Blog
<https://medium.com/aubergine-solutions> | Work-Portfolio
<https://www.behance.net/auberginesolutions>| Client-Testimonials
<https://clutch.co/profile/aubergine-solutions>
