### ISSUE TITLE
Some SVG images not importing

### ISSUE THREAD

**Issue by Subcide** [BuilderIO/html-to-figma#6]
SVGs in `<svg>` tags aren't being imported.

Example:
See Login button icon and navbar arrows on https://onfido.com/kyc/

**Comment by steve8708** [comment]
Ah interesting, looks like that's because the SVG contents are in shadow dom. Will take a look into supporting shadow dom shortly

**Comment by steve8708** [comment]
I also found a bug from that URL where the text formatting is all screwed up by including html whitespace when it shouldn't, fixing that now as well :)
