### ISSUE TITLE
Choose which screen size to import

### ISSUE THREAD

**Issue by Joshlenzlipitch** [BuilderIO/html-to-figma#9]
Would be cool if you could choose which size screen to import. This would mean you could import the mobile/tablet page too.

**Comment by steve8708** [comment]
hi @Joshlenzlipitch - thanks for the feedback, and you are in luck, this is already possible!

![import screen sizes](https://user-images.githubusercontent.com/844291/64192674-1bb35380-ce30-11e9-8f36-eba377c7a62e.gif)


I will make a note to make this more prominent and obvious too
